<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Tue, 29 Aug 2017 10:40:35 +0200
 */

$conf['title'] = 'wangqi0079';
$conf['lang'] = 'zh';
$conf['template'] = 'vector';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['proxy']['user'] = 'admin';
$conf['proxy']['pass'] = '<b>YWRtaW4=';

// end auto-generated content
